name: Bug Report
description: Create a bug report for Lock. 🐛
body:
  - type: textarea
    attributes:
      label: Describe the bug …
      description: A detailed description of the bug and it's consequences.
    validations:
      required: true
  - type: input
    attributes:
      label: Which version of Lock are you using?
      description: A software version, accessible via the about dialog
    validations:
      required: true
  - type: input
    attributes:
      label: Which version of GnuPG Made Easy is Lock using?
      description: A software version, accessible via console output of Lock
    validations:
      required: true
  - type: input
    attributes:
      label: Which distribution did this bug occur on?
      description: A Linux distribution
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Source
      description: How was Lock installed?
      options:
        - Flathub
        - Other Flatpak Repository
        - Other Package Manager
        - Build locally
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console Output (stdout)
      description: The output of Lock running in the command line.
      render: shell
    validations:
      required: true
